### ISSUE TITLE
Cards: Hyperlinked Cards Appear Blue On Mobile Apple Devices

### ISSUE THREAD

**Issue by rebeccagoldstein** [ASU/asu-unity-stack#1378]
Hyperlinked cards/cards with a hover link appear blue on mobile Apple devices due to Safari's user agent stylesheet.

Live example can be seen [here](https://new-sols2019.ws.asu.edu/about/mission-vision#) on an Apple device or simulator.

![Screenshot 2024-10-08 at 12 23 37 PM](https://github.com/user-attachments/assets/d9824d46-22b7-4aca-a820-e42ec2c2f913)

**Comment by mlsamuelson** [comment]
@rebeccagoldstein Thanks for the issue report. Our project's issue intake is via [Jira Service Desk](https://asudev.jira.com/servicedesk/customer/portal/2/group/29/create/92). If you could submit the ticket there, that'll ensure this is visible on our board and we can prioritize the work accordingly.

I believe I saw an access ticket you submitted in order to submit a pull request to resolve an issue.  As noted on the response to that ticket, the recommended workflow for that would be to fork the repo and submit a PR based on your fork. If you've already submitted the Jira Service Desk ticket, you could reference that with your PR.

Appreciate the issue report. I'm closing this in lieu of the above. If you have any questions, feel free to reach out.
